### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by sngehl01** [balena-io-playground/balena-datadog#4]
I'm trying to build/deploy this to my balena application. I'm getting a ton of errors after doing a push, the first is this 

[frontend]  debconf: delaying package configuration, since apt-utils is not installed
[debug] handling message: {"message":"\u001b[34m[frontend]\u001b[39m  \u001b[0m"}

followed by others like : 

[datadog]   debconf: delaying package configuration, since apt-utils is not installed

[datadog]     Failed building wheel for PyYAML

[datadog]     Failed building wheel for toml

and the list goes on. 

I have burned a blank balena OS image to my SD card. I downloaded this .zip for this repo and am trying to push it up from the parent directory and getting these errors. I'm not really sure how to proceed.

**Comment by cedricve** [comment]
same error, datadog is not building..

**Comment by chrisys** [comment]
I've just merged a long standing PR that was open and the project now builds and seems to work great once more!
